### ISSUE TITLE
No drop?

### ISSUE THREAD

**Issue by Pixle36** [raoulvdberge/refinedpipes#1]
Placed pipes when broken dont drop. Video [here](https://drive.google.com/file/d/1ZTnOr9v_aEi3SZ4UQXgKrpEBN9f9xt_-/view?usp=drivesdk)

**Comment by raoulvdberge** [comment]
Awkward! That's what I get for only testing in creative I guess...

**Comment by raoulvdberge** [comment]
Thanks for reporting, fixed.

**Comment by Pixle36** [comment]
No problem, I'll let u know if I find anymore bugs
