### ISSUE TITLE
Bigger reactors access ports can't accept or output items from chests when using these item pipes.

### ISSUE THREAD

**Issue by screret** [raoulvdberge/refinedpipes#111]
### Describe the bug

title

### How can we reproduce this bug or crash?

1. install Bigger Reactors with this mod
2. try to pipe uranium into a working reactor
3. it doesn't accept any items

### What Minecraft version is this happening on?

Minecraft 1.18.1

### What Forge version is this happening on?

39.0.76

### What Refined Pipes version is this happening on?

0.6.1

**Comment by raoulvdberge** [comment]
not refined pipes
