### ISSUE TITLE
Guys you literally can't place attachments

### ISSUE THREAD

**Issue by ThePetePandaPablo** [raoulvdberge/refinedpipes#113]
### Describe the bug

.

### How can we reproduce this bug or crash?

install mod 
go into game 
attachments cant be placed 
cry

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36226

### What Refined Pipes version is this happening on?

latest

**Comment by raoulvdberge** [comment]
Logs please

**Comment by Darkere** [comment]
Wasn't there a conflict with the diet mod that caused this?

**Comment by ThePetePandaPablo** [comment]
I have diet mod installed so will test without that. Will get you logs soon as I'm home from work
