### ISSUE TITLE
Oversending still a thing in 1.18.2

### ISSUE THREAD

**Issue by Lilygabe** [raoulvdberge/refinedpipes#118]
### Describe the bug

Whenever items are being sent to an almost full inventory, the pipe will send more items than can fit in the inventory, causing all extra items to spew out.

### How can we reproduce this bug or crash?

1. Fill a chest with items
2. Connect it to another chest using pipes
3. Put an extraction module on the empty chest side
4. Insert two stacks of items in the first chest
5. Remove one stack of items from the second chest
6. Depending on the extraction module type, up to 640 (64*10) items will be dropped into the world.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.92

### What Refined Pipes version is this happening on?

0.6.2

**Comment by raoulvdberge** [comment]
It's still a thing. Of course! The bug is still open: #5

So no need to create a new bug for the same thing.
