### ISSUE TITLE
Uncaught Exception causes fatal server crash. 

### ISSUE THREAD

**Issue by Gaiyamato** [raoulvdberge/refinedpipes#6]
Removing the last destination object from refined pipes with an active extractor causes an unrecoverable server crash due to an array out of bounds error. Required server rollback and complete removal of the mod to resolve. 
[crash-2020-04-26_01.28.44-server.txt](https://github.com/raoulvdberge/refinedpipes/files/4534459/crash-2020-04-26_01.28.44-server.txt)

**Comment by utoc** [comment]
We're having this issue as well on our server with the pack All the Mods 5.  

``	Forge: net.minecraftforge:31.1.63``
``		refinedpipes-0.4.jar Refined Pipes {refinedpipes@0.4 DONE}``

See attached crashlogs:

[crash-2020-05-03_17.31.08-server.txt](https://github.com/raoulvdberge/refinedpipes/files/4571867/crash-2020-05-03_17.31.08-server.txt)
[crash-2020-05-03_17.43.35-server.txt](https://github.com/raoulvdberge/refinedpipes/files/4571868/crash-2020-05-03_17.43.35-server.txt)
[crash-2020-05-03_18.02.58-server.txt](https://github.com/raoulvdberge/refinedpipes/files/4571869/crash-2020-05-03_18.02.58-server.txt)
[crash-2020-05-03_18.22.25-server.txt](https://github.com/raoulvdberge/refinedpipes/files/4571870/crash-2020-05-03_18.22.25-server.txt)

**Comment by Soneliver** [comment]
[crash-2020-05-05_00.37.37-server.txt](https://github.com/raoulvdberge/refinedpipes/files/4580523/crash-2020-05-05_00.37.37-server.txt)
hi, any idea for resolve this ? :s
