### ISSUE TITLE
[1.15.2] RP fluid pipes wont connect to RFTools Builder

### ISSUE THREAD

**Issue by Morpheus1101** [raoulvdberge/refinedpipes#9]
Forge: 31.1.9
RefinedPipes: 0.4

None of the Fluid Pipes will connect to the rftools builder machine, which is a valid block for pumping out fluids. 
![refinedpipes](https://user-images.githubusercontent.com/10524952/80892273-11718e00-8d0c-11ea-8822-16b79cea9537.png)

**Comment by Darkere** [comment]
The RFtools builder doesn't have a fluid inventory. It just places fluid in the tank above or below it. As such no fluid pipes will connect to it.
